workflows:
  android-workflow:
    name: Android Release Build
    max_build_duration: 120
    environment:
      flutter: stable
      java: 17
    
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
          
      - name: Flutter Clean
        script: |
          flutter clean
          
      - name: Build Optimized APK
        script: |
          flutter build apk --release \
            --obfuscate \
            --split-debug-info=build/app/outputs/symbols \
            --split-per-abi \
            --target-platform android-arm64 \
            --no-tree-shake-icons
          
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/symbols/**
      
    publishing:
      email:
        recipients:
          - admin@example.com # Ganti dengan email Anda
        notify:
          success: true
          failure: true
